---
- name: Install aptitude using apt
  apt: 
    name: aptitude
    state: present
    update_cache: true
    force_apt_get: true

- name: Install required system packages
  apt: 
    name: 
     - apt-transport-https 
     - ca-certificates
     - curl 
     - software-properties-common
     - python-pip
     - virtualenv
     - python-setuptools
    state: present
    update_cache: yes
    
    
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    
- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present


- name: Update and install
  apt:
    name: "*"
    state: present
    update_cache: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
- name: Install docker compose
  apt:
    name: docker-compose
    state: latest

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "started"
    enabled: true

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers